#  APRENDIZAJE AUTOMÁTICO - CLASE N°2
## Ejercicio N°1 - Importación y visualizacion de archivos .CSV ; .JSON y .XLS con Pandas

In [12]:
import pandas as pd

# Rutas en formato RAW de GitHub
url_clientes = "https://raw.githubusercontent.com/arieltunon74/Aprendizaje_Automatico_2026/main/Clase2/Ejercicio-1/clientes.json"
url_inventario = "https://raw.githubusercontent.com/arieltunon74/Aprendizaje_Automatico_2026/main/Clase2/Ejercicio-1/inventario.xlsx"
url_ventas = "https://raw.githubusercontent.com/arieltunon74/Aprendizaje_Automatico_2026/main/Clase2/Ejercicio-1/ventas.csv"

# Importar archivo JSON (Clientes)
df_clientes = pd.read_json(url_clientes).set_index("id_cliente")
print("--- Clientes ---")
display(df_clientes.head())

# Importar archivo Excel (Inventario)
df_inventario = pd.read_excel(url_inventario)
print("\n--- Inventario ---")
display(df_inventario.head())

# Importar archivo CSV (Ventas)
df_ventas = pd.read_csv(url_ventas, index_col="id_venta")
print("\n--- Ventas ---")
display(df_ventas.head())

--- Clientes ---

,nombre_completo,contacto,ubicacion,segmento,fecha_registro
id_cliente,,,,,
C102,Juan Pérez,"{'email': 'juan.perez@example.com', 'telefono'...","{'ciudad': 'Salta', 'pais': 'Argentina'}",Corporativo,2025-05-07
C205,María González,"{'email': 'maria.gonzalez@example.com', 'telef...","{'ciudad': 'Córdoba', 'pais': 'Argentina'}",Consumidor,2025-06-21
C118,Carlos Rodríguez,"{'email': 'carlos.rodriguez@example.com', 'tel...","{'ciudad': 'Córdoba', 'pais': 'Argentina'}",Corporativo,2025-12-21
C341,Ana Martínez,"{'email': 'ana.martinez@example.com', 'telefon...","{'ciudad': 'Buenos Aires', 'pais': 'Argentina'}",Consumidor,2025-11-10
C089,Lucas Fernández,"{'email': 'lucas.fernandez@example.com', 'tele...","{'ciudad': 'Mendoza', 'pais': 'Argentina'}",Pyme,2025-03-12

--- Inventario ---

,sku,producto,categoria,precio_venta,costo_unitario,ubicacion_almacen,stock_actual,stock_minimo,estado_stock,ultima_reposicion
0,PROD-0001,"Televisor 55""",Electrónica,450.0,310.0,Depósito Central,104,15,Óptimo,2026-07-20
1,PROD-0002,"Televisor 65""",Electrónica,720.0,500.0,Depósito Central,94,10,Óptimo,2026-07-15
2,PROD-0003,Teclado Mecánico,Computación,65.5,38.0,Sucursal Córdoba,108,30,Óptimo,2026-07-08
3,PROD-0004,"Monitor 27""",Computación,210.0,145.0,Depósito Central,62,10,Óptimo,2026-07-21
4,PROD-0005,Silla Gamer,Mobiliario,180.0,110.0,Sucursal Rosario,104,5,Óptimo,2026-07-26

--- Ventas ---

,fecha,producto,categoria,precio_unitario,costo_unitario,cantidad,descuento,id_cliente,ciudad,metodo_pago,estado_envio
id_venta,,,,,,,,,,,
V001,2026-08-01,Mouse Inalámbrico,Computación,25.0,12.0,4,0.20,C370,Rosario,Mercado Pago,Entregado
V002,2026-08-02,Barra de Sonido,Audio,130.0,85.0,3,0.10,C558,Río Grande,Efectivo,Entregado
V003,2026-08-03,Teclado Mecánico,Computación,65.5,38.0,5,0.05,C443,Mendoza,Tarjeta de Débito,Entregado
V004,2026-08-04,Silla Gamer,Mobiliario,180.0,110.0,1,0.15,C413,Tucumán,Mercado Pago,Entregado
V005,2026-08-05,"Televisor 55""",Electrónica,450.0,310.0,3,0.10,C610,Córdoba,Efectivo,Cancelado